[package]
name = "compile_with_bazel"
version = "0.0.0"

# Mandatory (or Cargo tooling is unhappy)
[lib]
path = "fake_lib.rs"

[dependencies]
cxx = "1.0.56"
structopt = "0.3.25"

[package.metadata.raze]
workspace_path = "//3rdparty/rust/cargo"
package_aliases_dir = "."
targets = [
    "x86_64-unknown-linux-gnu",
]
genmode = "Remote"
rust_rules_workspace_name = "rules_rust"

[package.metadata.raze.binary_deps]
cxxbridge-cmd = "1.0.56"

[package.metadata.raze.crates.cxxbridge-cmd.'*']
extra_aliased_targets = [
    "cargo_bin_cxxbridge"
]
compile_data_attr = "glob([\"**/*.h\"])"
